'use client'

import { useState, useEffect } from 'react'
import { X } from 'lucide-react'

const STORAGE_KEY = 'mygang-ai-disclaimer-dismissed'

export function AiDisclaimer() {
    const [visible, setVisible] = useState(false)

    useEffect(() => {
        try {
            const dismissed = localStorage.getItem(STORAGE_KEY)
            if (!dismissed) {
                setVisible(true)
            }
        } catch {
            // localStorage unavailable, don't show
        }
    }, [])

    if (!visible) return null

    const dismiss = () => {
        setVisible(false)
        try {
            localStorage.setItem(STORAGE_KEY, '1')
        } catch {
            // ignore
        }
    }

    return (
        <div className="mx-auto max-w-3xl w-full px-4 pt-2" data-screenshot-exclude="true">
            <div className="flex items-center justify-between gap-2 rounded-lg border border-border/40 bg-muted/30 px-3 py-1.5">
                <p className="text-[11px] text-muted-foreground/70 leading-relaxed">
                    Messages are generated by AI and may be inaccurate.
                </p>
                <button
                    type="button"
                    onClick={dismiss}
                    className="shrink-0 rounded-full p-0.5 text-muted-foreground/50 hover:text-muted-foreground transition-colors"
                    aria-label="Dismiss AI disclaimer"
                >
                    <X size={12} />
                </button>
            </div>
        </div>
    )
}
