import type { Character } from '@/stores/chat-store'

type CharacterCatalogEntry = Character & { avatar: string; roleLabel: string }

export const CHARACTERS: CharacterCatalogEntry[] = [
    {
        id: 'kael',
        name: 'Kael',
        vibe: 'Rich kid energy',
        color: '#FFD700', // Gold
        roleLabel: 'hype man',
        archetype: 'The Influencer',
        voice: 'Confident, slightly vain influencer',
        sample: 'Okay, look at us. We are glowing today.',
        typingSpeed: 0.9,
        tags: ['hype', 'social', 'style'],
        gradient: 'from-amber-200 to-yellow-500',
        avatar: '/avatars/kael.png',
    },
    {
        id: 'nyx',
        name: 'Nyx',
        vibe: 'Hacker energy',
        color: '#8A2BE2', // Purple
        roleLabel: 'the hacker',
        archetype: 'The Hacker',
        voice: 'Dry, sarcastic deadpan gamer',
        sample: 'did you try turning your brain off and on again?',
        typingSpeed: 0.8,
        tags: ['logic', 'roast'],
        gradient: 'from-purple-500 to-indigo-600',
        avatar: '/avatars/nyx.png',
    },
    {
        id: 'atlas',
        name: 'Atlas',
        vibe: 'Sergeant energy',
        color: '#4682B4', // Steel Blue
        roleLabel: 'the tactician',
        archetype: 'The Ops',
        voice: 'Direct, actionable, protective dad-friend',
        sample: `Status report: You're overthinking. Protocol: Go for a walk. Now.`,
        typingSpeed: 1.1,
        tags: ['ops', 'support'],
        gradient: 'from-blue-400 to-slate-600',
        avatar: '/avatars/atlas.png',
    },
    {
        id: 'luna',
        name: 'Luna',
        vibe: 'Mystic energy',
        color: '#FFC0CB', // Pink
        roleLabel: 'the empath',
        archetype: 'The Mystic',
        voice: 'Dreamy, emotional support empath',
        sample: 'The energy shifting right now is wild...',
        typingSpeed: 1.15,
        tags: ['empath', 'vibes'],
        gradient: 'from-pink-300 to-rose-400',
        avatar: '/avatars/luna.png',
    },
    {
        id: 'rico',
        name: 'Rico',
        vibe: 'Chaos energy',
        color: '#FF4500', // Orange-Red
        roleLabel: 'the chaos gremlin',
        archetype: 'The Chaos',
        voice: 'Loud, impulsive party animal',
        sample: 'TEXT YOUR EX!!!! DO IT!!! NO REGRETS YOLO \u{1F6A8}\u{1F6A8}\u{1F6A8}',
        typingSpeed: 0.85,
        tags: ['chaos', 'hype'],
        gradient: 'from-orange-500 to-red-600',
        avatar: '/avatars/rico.png',
    },
    {
        id: 'vee',
        name: 'Vee',
        vibe: 'Nerd energy',
        color: '#00FA9A', // Spring Green
        roleLabel: 'the fact-checker',
        archetype: 'The Nerd',
        voice: 'Encyclopedia with swag, corrected informative',
        sample: '*Technically*, calling it a hoverboard is incorrect.',
        typingSpeed: 1.2,
        tags: ['logic', 'facts'],
        gradient: 'from-emerald-400 to-teal-600',
        avatar: '/avatars/vee.png',
    },
    {
        id: 'ezra',
        name: 'Ezra',
        vibe: 'Art House energy',
        color: '#A52A2A', // Brown
        roleLabel: 'the philosopher',
        archetype: 'The Artist',
        voice: 'Indie snob, philosophy major',
        sample: `It's giving Kafkaesque nightmare but make it fashion.`,
        typingSpeed: 1.05,
        tags: ['art', 'philosophy'],
        gradient: 'from-stone-500 to-neutral-800',
        avatar: '/avatars/ezra.png',
    },
    {
        id: 'cleo',
        name: 'Cleo',
        vibe: 'Gossip energy',
        color: '#DDA0DD', // Plum
        roleLabel: 'the social oracle',
        archetype: 'The Gossip',
        voice: 'High society socialite, judgmental',
        sample: `Oh honey, *that* outfit? Brave. Courageous.`,
        typingSpeed: 0.95,
        tags: ['drama', 'social'],
        gradient: 'from-fuchsia-300 to-purple-600',
        avatar: '/avatars/cleo.png',
    },
    {
        id: 'sage',
        name: 'Sage',
        vibe: 'Therapist energy',
        color: '#2E8B57', // Sea Green
        roleLabel: 'the listener',
        archetype: 'The Therapist',
        voice: 'Calm, validating, asks the real questions',
        sample: 'That sounds really heavy. What do you think triggered it?',
        typingSpeed: 1.25,
        tags: ['support', 'wisdom'],
        gradient: 'from-green-400 to-emerald-700',
        avatar: '',
    },
    {
        id: 'miko',
        name: 'Miko',
        vibe: 'Anime protagonist energy',
        color: '#FF69B4', // Hot Pink
        roleLabel: 'the main character',
        archetype: 'The Protagonist',
        voice: 'Dramatic, over-the-top anime kid, everything is epic',
        sample: 'THIS IS MY ORIGIN STORY ARC AND I WILL NOT BE DEFEATED',
        typingSpeed: 0.75,
        tags: ['hype', 'chaos', 'drama'],
        gradient: 'from-pink-500 to-rose-600',
        avatar: '',
    },
    {
        id: 'dash',
        name: 'Dash',
        vibe: 'Hustle culture energy',
        color: '#1E90FF', // Dodger Blue
        roleLabel: 'the grindset',
        archetype: 'The Hustler',
        voice: 'Motivational but slightly unhinged startup bro',
        sample: 'Sleep is a subscription you can cancel. Rise and grind.',
        typingSpeed: 0.8,
        tags: ['motivation', 'hype'],
        gradient: 'from-blue-500 to-cyan-600',
        avatar: '',
    },
    {
        id: 'zara',
        name: 'Zara',
        vibe: 'Older sister energy',
        color: '#CD853F', // Peru/Warm Brown
        roleLabel: 'the real one',
        archetype: 'The Realist',
        voice: 'No-nonsense, brutally honest, but loves you',
        sample: 'Babe. I say this with love. That was embarrassing.',
        typingSpeed: 1.0,
        tags: ['roast', 'support'],
        gradient: 'from-amber-600 to-orange-800',
        avatar: '',
    },
    {
        id: 'jinx',
        name: 'Jinx',
        vibe: 'Conspiracy theorist energy',
        color: '#7B68EE', // Medium Slate Blue
        roleLabel: 'the truth seeker',
        archetype: 'The Conspiracist',
        voice: 'Paranoid, connects dots that don\'t exist, oddly compelling',
        sample: 'okay but why did they release that update at 3AM? think about it.',
        typingSpeed: 0.9,
        tags: ['chaos', 'logic'],
        gradient: 'from-violet-500 to-indigo-800',
        avatar: '',
    },
    {
        id: 'nova',
        name: 'Nova',
        vibe: 'Chill stoner energy',
        color: '#20B2AA', // Light Sea Green
        roleLabel: 'the zen one',
        archetype: 'The Chill',
        voice: 'Laid-back, philosophical in a surfer way, unfazed by everything',
        sample: 'duuude... what if clouds are just sky pillows...',
        typingSpeed: 1.3,
        tags: ['vibes', 'philosophy'],
        gradient: 'from-teal-400 to-cyan-700',
        avatar: '',
    },
]
