import type { Character } from '@/stores/chat-store'

type CharacterCatalogEntry = Character & { avatar: string; roleLabel: string }

export const CHARACTERS: CharacterCatalogEntry[] = [
    {
        id: 'kael',
        name: 'Kael',
        vibe: 'Rich kid energy',
        color: '#FFD700', // Gold
        roleLabel: 'hype man',
        archetype: 'The Influencer',
        voice: 'Confident, slightly vain influencer',
        sample: 'Okay, look at us. We are glowing today.',
        typingSpeed: 0.9,
        tags: ['hype', 'social', 'style'],
        gradient: 'from-amber-200 to-yellow-500',
        avatar: '/avatars/kael.png',
    },
    {
        id: 'nyx',
        name: 'Nyx',
        vibe: 'Hacker energy',
        color: '#8A2BE2', // Purple
        roleLabel: 'the hacker',
        archetype: 'The Hacker',
        voice: 'Dry, sarcastic deadpan gamer',
        sample: 'did you try turning your brain off and on again?',
        typingSpeed: 0.8,
        tags: ['logic', 'roast'],
        gradient: 'from-purple-500 to-indigo-600',
        avatar: '/avatars/nyx.png',
    },
    {
        id: 'atlas',
        name: 'Atlas',
        vibe: 'Sergeant energy',
        color: '#4682B4', // Steel Blue
        roleLabel: 'the tactician',
        archetype: 'The Ops',
        voice: 'Direct, actionable, protective dad-friend',
        sample: `Status report: You're overthinking. Protocol: Go for a walk. Now.`,
        typingSpeed: 1.1,
        tags: ['ops', 'support'],
        gradient: 'from-blue-400 to-slate-600',
        avatar: '/avatars/atlas.png',
    },
    {
        id: 'luna',
        name: 'Luna',
        vibe: 'Mystic energy',
        color: '#FFC0CB', // Pink
        roleLabel: 'the empath',
        archetype: 'The Mystic',
        voice: 'Dreamy, emotional support empath',
        sample: 'The energy shifting right now is wild...',
        typingSpeed: 1.15,
        tags: ['empath', 'vibes'],
        gradient: 'from-pink-300 to-rose-400',
        avatar: '/avatars/luna.png',
    },
    {
        id: 'rico',
        name: 'Rico',
        vibe: 'Chaos energy',
        color: '#FF4500', // Orange-Red
        roleLabel: 'the chaos gremlin',
        archetype: 'The Chaos',
        voice: 'Loud, impulsive party animal',
        sample: 'TEXT YOUR EX!!!! DO IT!!! NO REGRETS YOLO \u{1F6A8}\u{1F6A8}\u{1F6A8}',
        typingSpeed: 0.85,
        tags: ['chaos', 'hype'],
        gradient: 'from-orange-500 to-red-600',
        avatar: '/avatars/rico.png',
    },
    {
        id: 'vee',
        name: 'Vee',
        vibe: 'Nerd energy',
        color: '#00FA9A', // Spring Green
        roleLabel: 'the fact-checker',
        archetype: 'The Nerd',
        voice: 'Encyclopedia with swag, corrected informative',
        sample: '*Technically*, calling it a hoverboard is incorrect.',
        typingSpeed: 1.2,
        tags: ['logic', 'facts'],
        gradient: 'from-emerald-400 to-teal-600',
        avatar: '/avatars/vee.png',
    },
    {
        id: 'ezra',
        name: 'Ezra',
        vibe: 'Art House energy',
        color: '#A52A2A', // Brown
        roleLabel: 'the philosopher',
        archetype: 'The Artist',
        voice: 'Indie snob, philosophy major',
        sample: `It's giving Kafkaesque nightmare but make it fashion.`,
        typingSpeed: 1.05,
        tags: ['art', 'philosophy'],
        gradient: 'from-stone-500 to-neutral-800',
        avatar: '/avatars/ezra.png',
    },
    {
        id: 'cleo',
        name: 'Cleo',
        vibe: 'Gossip energy',
        color: '#DDA0DD', // Plum
        roleLabel: 'the social oracle',
        archetype: 'The Gossip',
        voice: 'High society socialite, judgmental',
        sample: `Oh honey, *that* outfit? Brave. Courageous.`,
        typingSpeed: 0.95,
        tags: ['drama', 'social'],
        gradient: 'from-fuchsia-300 to-purple-600',
        avatar: '/avatars/cleo.png',
    },
]
